runtime: python312
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

env_variables:
  OPENAI_API_KEY: "insert_your_api_key_here"  # Or you can skip this if you're deploying with them in Secret Manager
